default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: <%= ENV['POSTGRES_USER'] {'postgres'}%>
  password: <%= ENV['POSTGRES_PASSWORD'] {'postgres'} %>

development:
  <<: *default
  database: tech_test_development

test:
  <<: *default
  host: <%= ENV['POSTGRES_HOST'] {'localhost'} %>
  user: <%= ENV['POSTGRES_USER'] {'postgres'}%>
  password: <%= ENV['POSTGRES_PASSWORD'] {'postgres'} %>
  database: tech_test_test

production:
  primary: &primary_production
    <<: *default
    database: tech_test_production
    username: nonreserved
    password: <%= ENV["TECH_TEST_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: tech_test_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: tech_test_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: tech_test_production_cable
    migrations_paths: db/cable_migrate
